### ISSUE TITLE
Remove metadata reading in the github actions

### ISSUE THREAD

**Issue by Caaz** [Caaz/rimworld-creepers#7]
This step of the workflow reads a variable, to be used by the upload action.
https://github.com/Caaz/rimworld-creepers/blob/main/.github/workflows/Build.yml#L17-L21

We should remove that step, and modify the following line
https://github.com/Caaz/rimworld-creepers/blob/main/.github/workflows/Build.yml#L27
By uploading the action simply as "Creepers"

**Comment by m-bartlett** [comment]
Would something like 
```yaml
env:
  mod_name: Creepers

# ...

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.mod_name }}
```

be preferable?
